### ISSUE TITLE
Nitpick: don't like the "chorus" and "composer" component names

### ISSUE THREAD

**Issue by kevin-alpine** [Chorus/ensemble#4]
@prakash-alpine: I totally see what you were going for with the `chorus` & `composer` names but, their meanings aren't intuitive to me.

For these two only, I suggest we choose more "brain dead" obvious names:
chorus -> frontend
composer -> admin

Maybe you have more thinking behind -- can you walk me through that?  Just, now at the start, wanted to communicate my reaction to those two specifically.

**Comment by prakash-alpine** [comment]
OK. It makes sense. I am a music buff and I like the analogy of ensemble and Composer with Chorus. It rhymes well to-gather. I will change them.

Prakash
